// ********RoostGPT********
/*
Test generated by RoostGPT for test java-junit4-test using AI Type Open AI and AI Model gpt-4

Test generated for /api/customer/restaurantTable/create_post for http method type POST in rest-assured framework

RoostTestHash=6c5accfb60


*/

// ********RoostGPT********
package com.medeiros.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class createPostTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      envList = dataloader.loadData("src/test/java/com/medeiros/RoostTest/createPostTest.csv");
    }

  
    @Test  
    public void createPost_Test() {
        this.setUp();
        for (Map<String, String> map : envList) {
          RestAssured.baseURI = map.get("BASE_URL");  
  
                Response response = given()
				.pathParam("company", map.get("company") != null ? map.get("company") : "")
				.pathParam("tableGroupId", map.get("tableGroupId") != null ? map.get("tableGroupId") : "")
				.pathParam("number", map.get("number") != null ? map.get("number") : "")
				.pathParam("name", map.get("name") != null ? map.get("name") : "")
				.pathParam("externalId", map.get("externalId") != null ? map.get("externalId") : "")
				.header("Authorization", "Bearer " + map.get("AUTH_TOKEN"))
                .when()
                .post("/api/customer/restaurantTable/create")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: Create new Restaurant Table");
      
              if (response.jsonPath().get("id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("id"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("external_id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("external_id"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("number") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("number"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("name") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("name"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("restaurant_table_group_id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("restaurant_table_group_id"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("updated_at") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("updated_at"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("created_at") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("created_at"), instanceOf(String.class));  
          }
				}
  
            }  
    }
}
